package com.example.domain.repository.passwordhistory;

import com.example.domain.model.PasswordHistory;
import com.example.domain.model.PasswordHistoryExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.time.LocalDateTime;
import java.util.List;

public interface PasswordHistoryRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    long countByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("useFrom") LocalDateTime useFrom);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int insert(PasswordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int insertSelective(PasswordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    List<PasswordHistory> selectByExampleWithRowbounds(PasswordHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    List<PasswordHistory> selectByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    PasswordHistory selectByPrimaryKey(@Param("username") String username, @Param("useFrom") LocalDateTime useFrom);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PasswordHistory record, @Param("example") PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PasswordHistory record, @Param("example") PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordHistory record);
}