package com.example.domain.repository.passwordreissue;

import com.example.domain.model.FailedPasswordReissue;
import com.example.domain.model.FailedPasswordReissueExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FailedPasswordReissueRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    long countByExample(FailedPasswordReissueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int deleteByExample(FailedPasswordReissueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("token") String token, @Param("attemptDate") LocalDateTime attemptDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int insert(FailedPasswordReissue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int insertSelective(FailedPasswordReissue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    List<FailedPasswordReissue> selectByExampleWithRowbounds(FailedPasswordReissueExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    List<FailedPasswordReissue> selectByExample(FailedPasswordReissueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FailedPasswordReissue record, @Param("example") FailedPasswordReissueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_password_reissue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FailedPasswordReissue record, @Param("example") FailedPasswordReissueExample example);
}