package com.example.domain.repository.passwordreissue;

import com.example.domain.model.PasswordReissueInfo;
import com.example.domain.model.PasswordReissueInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface PasswordReissueInfoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    long countByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int insert(PasswordReissueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int insertSelective(PasswordReissueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    List<PasswordReissueInfo> selectByExampleWithRowbounds(PasswordReissueInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    List<PasswordReissueInfo> selectByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    PasswordReissueInfo selectByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PasswordReissueInfo record, @Param("example") PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PasswordReissueInfo record, @Param("example") PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordReissueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordReissueInfo record);
}