package com.example.domain.repository.authenticationevent;

import com.example.domain.model.FailedAuthentication;
import com.example.domain.model.FailedAuthenticationExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FailedAuthenticationRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    long countByExample(FailedAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int deleteByExample(FailedAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("authenticationTimestamp") LocalDateTime authenticationTimestamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int insert(FailedAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int insertSelective(FailedAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    List<FailedAuthentication> selectByExampleWithRowbounds(FailedAuthenticationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    List<FailedAuthentication> selectByExample(FailedAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FailedAuthentication record, @Param("example") FailedAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FailedAuthentication record, @Param("example") FailedAuthenticationExample example);
}