package com.example.domain.repository.authenticationevent;

import com.example.domain.model.SuccessfulAuthentication;
import com.example.domain.model.SuccessfulAuthenticationExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SuccessfulAuthenticationRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    long countByExample(SuccessfulAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int deleteByExample(SuccessfulAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("authenticationTimestamp") LocalDateTime authenticationTimestamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int insert(SuccessfulAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int insertSelective(SuccessfulAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    List<SuccessfulAuthentication> selectByExampleWithRowbounds(SuccessfulAuthenticationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    List<SuccessfulAuthentication> selectByExample(SuccessfulAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SuccessfulAuthentication record, @Param("example") SuccessfulAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successful_authentication
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SuccessfulAuthentication record, @Param("example") SuccessfulAuthenticationExample example);
}