package com.example.domain.repository.example;

import com.example.domain.example.StaffRev;
import com.example.domain.example.StaffRevExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface StaffRevRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    long countByExample(StaffRevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int deleteByExample(StaffRevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Long id, @Param("version") Long version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int insert(StaffRev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int insertSelective(StaffRev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    List<StaffRev> selectByExampleWithRowbounds(StaffRevExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    List<StaffRev> selectByExample(StaffRevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    StaffRev selectByPrimaryKey(@Param("id") Long id, @Param("version") Long version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffRev record, @Param("example") StaffRevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffRev record, @Param("example") StaffRevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(StaffRev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffRev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(StaffRev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_rev
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffRev record);
}