package com.example.domain.repository.example;

import com.example.domain.example.StaffView;
import com.example.domain.example.StaffViewExample;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface StaffViewRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_view
     *
     * @mbg.generated
     */
    long countByExample(StaffViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_view
     *
     * @mbg.generated
     */
    List<StaffView> selectByExampleWithRowbounds(StaffViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_view
     *
     * @mbg.generated
     */
    List<StaffView> selectByExample(StaffViewExample example);
}