package com.example.domain.repository.asg;

import com.example.domain.model.TtJoho;
import com.example.domain.model.TtJohoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TtJohoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    long countByExample(TtJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int deleteByExample(TtJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal cdSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int insert(TtJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int insertSelective(TtJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    List<TtJoho> selectByExampleWithRowbounds(TtJohoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    List<TtJoho> selectByExample(TtJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    TtJoho selectByPrimaryKey(BigDecimal cdSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TtJoho record, @Param("example") TtJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TtJoho record, @Param("example") TtJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TtJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TtJoho record);
}