package com.example.domain.example;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Database Table Remarks:
 * サンプル１
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sample1
 */
@Data
@Builder
@Accessors(chain = true)
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@ToString(callSuper = true)
public class Sample1 extends AbstractLombokEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * 数値・整数１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.integer_number
     *
     * @mbg.generated
     */
    @NonNull
    private Integer integerNumber;
    /**
     * Database Column Remarks:
     * 数値・整数２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.real_number
     *
     * @mbg.generated
     */
    private Float realNumber;
    /**
     * Database Column Remarks:
     * 数値・小数１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.double_precision_number
     *
     * @mbg.generated
     */
    private Double doublePrecisionNumber;
    /**
     * Database Column Remarks:
     * 数値・小数２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.decimal_number
     *
     * @mbg.generated
     */
    private BigDecimal decimalNumber;
    /**
     * Database Column Remarks:
     * 数値・連番
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.serial_number
     *
     * @mbg.generated
     */
    @NonNull
    private Integer serialNumber;
    /**
     * Database Column Remarks:
     * 文字列・可変長１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.character_varying_string
     *
     * @mbg.generated
     */
    private String characterVaryingString;
    /**
     * Database Column Remarks:
     * 文字列・可変長２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.varchar_string
     *
     * @mbg.generated
     */
    private String varcharString;
    /**
     * Database Column Remarks:
     * 文字列・固定長１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.character_string
     *
     * @mbg.generated
     */
    private String characterString;
    /**
     * Database Column Remarks:
     * 文字列・固定長２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.char_string
     *
     * @mbg.generated
     */
    private String charString;
    /**
     * Database Column Remarks:
     * 文字列・テキスト
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.text_string
     *
     * @mbg.generated
     */
    private String textString;
    /**
     * Database Column Remarks:
     * 日付・日付
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.date_data
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd")
    private LocalDate dateData;
    /**
     * Database Column Remarks:
     * 日付・時刻１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.time_data
     *
     * @mbg.generated
     */
    private LocalTime timeData;
    /**
     * Database Column Remarks:
     * 日付・時刻２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.time_zone_data
     *
     * @mbg.generated
     */
    private LocalTime timeZoneData;
    /**
     * Database Column Remarks:
     * 日付・日時１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.timestamp_data
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime timestampData;
    /**
     * Database Column Remarks:
     * 日付・日時２
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.timestamp_zone_data
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime timestampZoneData;
    /**
     * Database Column Remarks:
     * 真偽値１
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.boolean_boolean
     *
     * @mbg.generated
     */
    private Boolean booleanBoolean;
    /**
     * Database Column Remarks:
     * バイナリ
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.binary_binary
     *
     * @mbg.generated
     */
    private byte[] binaryBinary;
}