package com.example.domain.example;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class Sample1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample1
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample1
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample1
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public Sample1Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample1
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIntegerNumberIsNull() {
            addCriterion("integer_number is null");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberIsNotNull() {
            addCriterion("integer_number is not null");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberEqualTo(Integer value) {
            addCriterion("integer_number =", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberNotEqualTo(Integer value) {
            addCriterion("integer_number <>", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberGreaterThan(Integer value) {
            addCriterion("integer_number >", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("integer_number >=", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberLessThan(Integer value) {
            addCriterion("integer_number <", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberLessThanOrEqualTo(Integer value) {
            addCriterion("integer_number <=", value, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberIn(List<Integer> values) {
            addCriterion("integer_number in", values, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberNotIn(List<Integer> values) {
            addCriterion("integer_number not in", values, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberBetween(Integer value1, Integer value2) {
            addCriterion("integer_number between", value1, value2, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andIntegerNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("integer_number not between", value1, value2, "integerNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberIsNull() {
            addCriterion("real_number is null");
            return (Criteria) this;
        }

        public Criteria andRealNumberIsNotNull() {
            addCriterion("real_number is not null");
            return (Criteria) this;
        }

        public Criteria andRealNumberEqualTo(Float value) {
            addCriterion("real_number =", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberNotEqualTo(Float value) {
            addCriterion("real_number <>", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberGreaterThan(Float value) {
            addCriterion("real_number >", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberGreaterThanOrEqualTo(Float value) {
            addCriterion("real_number >=", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberLessThan(Float value) {
            addCriterion("real_number <", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberLessThanOrEqualTo(Float value) {
            addCriterion("real_number <=", value, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberIn(List<Float> values) {
            addCriterion("real_number in", values, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberNotIn(List<Float> values) {
            addCriterion("real_number not in", values, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberBetween(Float value1, Float value2) {
            addCriterion("real_number between", value1, value2, "realNumber");
            return (Criteria) this;
        }

        public Criteria andRealNumberNotBetween(Float value1, Float value2) {
            addCriterion("real_number not between", value1, value2, "realNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberIsNull() {
            addCriterion("double_precision_number is null");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberIsNotNull() {
            addCriterion("double_precision_number is not null");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberEqualTo(Double value) {
            addCriterion("double_precision_number =", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberNotEqualTo(Double value) {
            addCriterion("double_precision_number <>", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberGreaterThan(Double value) {
            addCriterion("double_precision_number >", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberGreaterThanOrEqualTo(Double value) {
            addCriterion("double_precision_number >=", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberLessThan(Double value) {
            addCriterion("double_precision_number <", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberLessThanOrEqualTo(Double value) {
            addCriterion("double_precision_number <=", value, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberIn(List<Double> values) {
            addCriterion("double_precision_number in", values, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberNotIn(List<Double> values) {
            addCriterion("double_precision_number not in", values, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberBetween(Double value1, Double value2) {
            addCriterion("double_precision_number between", value1, value2, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDoublePrecisionNumberNotBetween(Double value1, Double value2) {
            addCriterion("double_precision_number not between", value1, value2, "doublePrecisionNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberIsNull() {
            addCriterion("decimal_number is null");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberIsNotNull() {
            addCriterion("decimal_number is not null");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberEqualTo(BigDecimal value) {
            addCriterion("decimal_number =", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberNotEqualTo(BigDecimal value) {
            addCriterion("decimal_number <>", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberGreaterThan(BigDecimal value) {
            addCriterion("decimal_number >", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("decimal_number >=", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberLessThan(BigDecimal value) {
            addCriterion("decimal_number <", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("decimal_number <=", value, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberIn(List<BigDecimal> values) {
            addCriterion("decimal_number in", values, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberNotIn(List<BigDecimal> values) {
            addCriterion("decimal_number not in", values, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decimal_number between", value1, value2, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andDecimalNumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("decimal_number not between", value1, value2, "decimalNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNull() {
            addCriterion("serial_number is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNotNull() {
            addCriterion("serial_number is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberEqualTo(Integer value) {
            addCriterion("serial_number =", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotEqualTo(Integer value) {
            addCriterion("serial_number <>", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThan(Integer value) {
            addCriterion("serial_number >", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("serial_number >=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThan(Integer value) {
            addCriterion("serial_number <", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThanOrEqualTo(Integer value) {
            addCriterion("serial_number <=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIn(List<Integer> values) {
            addCriterion("serial_number in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotIn(List<Integer> values) {
            addCriterion("serial_number not in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberBetween(Integer value1, Integer value2) {
            addCriterion("serial_number between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("serial_number not between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringIsNull() {
            addCriterion("character_varying_string is null");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringIsNotNull() {
            addCriterion("character_varying_string is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringEqualTo(String value) {
            addCriterion("character_varying_string =", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringNotEqualTo(String value) {
            addCriterion("character_varying_string <>", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringGreaterThan(String value) {
            addCriterion("character_varying_string >", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringGreaterThanOrEqualTo(String value) {
            addCriterion("character_varying_string >=", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringLessThan(String value) {
            addCriterion("character_varying_string <", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringLessThanOrEqualTo(String value) {
            addCriterion("character_varying_string <=", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringLike(String value) {
            addCriterion("character_varying_string like", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringNotLike(String value) {
            addCriterion("character_varying_string not like", value, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringIn(List<String> values) {
            addCriterion("character_varying_string in", values, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringNotIn(List<String> values) {
            addCriterion("character_varying_string not in", values, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringBetween(String value1, String value2) {
            addCriterion("character_varying_string between", value1, value2, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringNotBetween(String value1, String value2) {
            addCriterion("character_varying_string not between", value1, value2, "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringIsNull() {
            addCriterion("varchar_string is null");
            return (Criteria) this;
        }

        public Criteria andVarcharStringIsNotNull() {
            addCriterion("varchar_string is not null");
            return (Criteria) this;
        }

        public Criteria andVarcharStringEqualTo(String value) {
            addCriterion("varchar_string =", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringNotEqualTo(String value) {
            addCriterion("varchar_string <>", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringGreaterThan(String value) {
            addCriterion("varchar_string >", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringGreaterThanOrEqualTo(String value) {
            addCriterion("varchar_string >=", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringLessThan(String value) {
            addCriterion("varchar_string <", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringLessThanOrEqualTo(String value) {
            addCriterion("varchar_string <=", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringLike(String value) {
            addCriterion("varchar_string like", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringNotLike(String value) {
            addCriterion("varchar_string not like", value, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringIn(List<String> values) {
            addCriterion("varchar_string in", values, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringNotIn(List<String> values) {
            addCriterion("varchar_string not in", values, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringBetween(String value1, String value2) {
            addCriterion("varchar_string between", value1, value2, "varcharString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringNotBetween(String value1, String value2) {
            addCriterion("varchar_string not between", value1, value2, "varcharString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringIsNull() {
            addCriterion("character_string is null");
            return (Criteria) this;
        }

        public Criteria andCharacterStringIsNotNull() {
            addCriterion("character_string is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterStringEqualTo(String value) {
            addCriterion("character_string =", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringNotEqualTo(String value) {
            addCriterion("character_string <>", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringGreaterThan(String value) {
            addCriterion("character_string >", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringGreaterThanOrEqualTo(String value) {
            addCriterion("character_string >=", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringLessThan(String value) {
            addCriterion("character_string <", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringLessThanOrEqualTo(String value) {
            addCriterion("character_string <=", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringLike(String value) {
            addCriterion("character_string like", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringNotLike(String value) {
            addCriterion("character_string not like", value, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringIn(List<String> values) {
            addCriterion("character_string in", values, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringNotIn(List<String> values) {
            addCriterion("character_string not in", values, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringBetween(String value1, String value2) {
            addCriterion("character_string between", value1, value2, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringNotBetween(String value1, String value2) {
            addCriterion("character_string not between", value1, value2, "characterString");
            return (Criteria) this;
        }

        public Criteria andCharStringIsNull() {
            addCriterion("char_string is null");
            return (Criteria) this;
        }

        public Criteria andCharStringIsNotNull() {
            addCriterion("char_string is not null");
            return (Criteria) this;
        }

        public Criteria andCharStringEqualTo(String value) {
            addCriterion("char_string =", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringNotEqualTo(String value) {
            addCriterion("char_string <>", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringGreaterThan(String value) {
            addCriterion("char_string >", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringGreaterThanOrEqualTo(String value) {
            addCriterion("char_string >=", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringLessThan(String value) {
            addCriterion("char_string <", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringLessThanOrEqualTo(String value) {
            addCriterion("char_string <=", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringLike(String value) {
            addCriterion("char_string like", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringNotLike(String value) {
            addCriterion("char_string not like", value, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringIn(List<String> values) {
            addCriterion("char_string in", values, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringNotIn(List<String> values) {
            addCriterion("char_string not in", values, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringBetween(String value1, String value2) {
            addCriterion("char_string between", value1, value2, "charString");
            return (Criteria) this;
        }

        public Criteria andCharStringNotBetween(String value1, String value2) {
            addCriterion("char_string not between", value1, value2, "charString");
            return (Criteria) this;
        }

        public Criteria andTextStringIsNull() {
            addCriterion("text_string is null");
            return (Criteria) this;
        }

        public Criteria andTextStringIsNotNull() {
            addCriterion("text_string is not null");
            return (Criteria) this;
        }

        public Criteria andTextStringEqualTo(String value) {
            addCriterion("text_string =", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringNotEqualTo(String value) {
            addCriterion("text_string <>", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringGreaterThan(String value) {
            addCriterion("text_string >", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringGreaterThanOrEqualTo(String value) {
            addCriterion("text_string >=", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringLessThan(String value) {
            addCriterion("text_string <", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringLessThanOrEqualTo(String value) {
            addCriterion("text_string <=", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringLike(String value) {
            addCriterion("text_string like", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringNotLike(String value) {
            addCriterion("text_string not like", value, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringIn(List<String> values) {
            addCriterion("text_string in", values, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringNotIn(List<String> values) {
            addCriterion("text_string not in", values, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringBetween(String value1, String value2) {
            addCriterion("text_string between", value1, value2, "textString");
            return (Criteria) this;
        }

        public Criteria andTextStringNotBetween(String value1, String value2) {
            addCriterion("text_string not between", value1, value2, "textString");
            return (Criteria) this;
        }

        public Criteria andDateDataIsNull() {
            addCriterion("date_data is null");
            return (Criteria) this;
        }

        public Criteria andDateDataIsNotNull() {
            addCriterion("date_data is not null");
            return (Criteria) this;
        }

        public Criteria andDateDataEqualTo(LocalDate value) {
            addCriterion("date_data =", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataNotEqualTo(LocalDate value) {
            addCriterion("date_data <>", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataGreaterThan(LocalDate value) {
            addCriterion("date_data >", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataGreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date_data >=", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataLessThan(LocalDate value) {
            addCriterion("date_data <", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataLessThanOrEqualTo(LocalDate value) {
            addCriterion("date_data <=", value, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataIn(List<LocalDate> values) {
            addCriterion("date_data in", values, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataNotIn(List<LocalDate> values) {
            addCriterion("date_data not in", values, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date_data between", value1, value2, "dateData");
            return (Criteria) this;
        }

        public Criteria andDateDataNotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date_data not between", value1, value2, "dateData");
            return (Criteria) this;
        }

        public Criteria andTimeDataIsNull() {
            addCriterion("time_data is null");
            return (Criteria) this;
        }

        public Criteria andTimeDataIsNotNull() {
            addCriterion("time_data is not null");
            return (Criteria) this;
        }

        public Criteria andTimeDataEqualTo(LocalTime value) {
            addCriterion("time_data =", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataNotEqualTo(LocalTime value) {
            addCriterion("time_data <>", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataGreaterThan(LocalTime value) {
            addCriterion("time_data >", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataGreaterThanOrEqualTo(LocalTime value) {
            addCriterion("time_data >=", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataLessThan(LocalTime value) {
            addCriterion("time_data <", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataLessThanOrEqualTo(LocalTime value) {
            addCriterion("time_data <=", value, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataIn(List<LocalTime> values) {
            addCriterion("time_data in", values, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataNotIn(List<LocalTime> values) {
            addCriterion("time_data not in", values, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataBetween(LocalTime value1, LocalTime value2) {
            addCriterion("time_data between", value1, value2, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeDataNotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("time_data not between", value1, value2, "timeData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataIsNull() {
            addCriterion("time_zone_data is null");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataIsNotNull() {
            addCriterion("time_zone_data is not null");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataEqualTo(LocalTime value) {
            addCriterion("time_zone_data =", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataNotEqualTo(LocalTime value) {
            addCriterion("time_zone_data <>", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataGreaterThan(LocalTime value) {
            addCriterion("time_zone_data >", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataGreaterThanOrEqualTo(LocalTime value) {
            addCriterion("time_zone_data >=", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataLessThan(LocalTime value) {
            addCriterion("time_zone_data <", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataLessThanOrEqualTo(LocalTime value) {
            addCriterion("time_zone_data <=", value, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataIn(List<LocalTime> values) {
            addCriterion("time_zone_data in", values, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataNotIn(List<LocalTime> values) {
            addCriterion("time_zone_data not in", values, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataBetween(LocalTime value1, LocalTime value2) {
            addCriterion("time_zone_data between", value1, value2, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimeZoneDataNotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("time_zone_data not between", value1, value2, "timeZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataIsNull() {
            addCriterion("timestamp_data is null");
            return (Criteria) this;
        }

        public Criteria andTimestampDataIsNotNull() {
            addCriterion("timestamp_data is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampDataEqualTo(LocalDateTime value) {
            addCriterion("timestamp_data =", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataNotEqualTo(LocalDateTime value) {
            addCriterion("timestamp_data <>", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataGreaterThan(LocalDateTime value) {
            addCriterion("timestamp_data >", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("timestamp_data >=", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataLessThan(LocalDateTime value) {
            addCriterion("timestamp_data <", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("timestamp_data <=", value, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataIn(List<LocalDateTime> values) {
            addCriterion("timestamp_data in", values, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataNotIn(List<LocalDateTime> values) {
            addCriterion("timestamp_data not in", values, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("timestamp_data between", value1, value2, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampDataNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("timestamp_data not between", value1, value2, "timestampData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataIsNull() {
            addCriterion("timestamp_zone_data is null");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataIsNotNull() {
            addCriterion("timestamp_zone_data is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataEqualTo(LocalDateTime value) {
            addCriterion("timestamp_zone_data =", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataNotEqualTo(LocalDateTime value) {
            addCriterion("timestamp_zone_data <>", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataGreaterThan(LocalDateTime value) {
            addCriterion("timestamp_zone_data >", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("timestamp_zone_data >=", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataLessThan(LocalDateTime value) {
            addCriterion("timestamp_zone_data <", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("timestamp_zone_data <=", value, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataIn(List<LocalDateTime> values) {
            addCriterion("timestamp_zone_data in", values, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataNotIn(List<LocalDateTime> values) {
            addCriterion("timestamp_zone_data not in", values, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("timestamp_zone_data between", value1, value2, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andTimestampZoneDataNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("timestamp_zone_data not between", value1, value2, "timestampZoneData");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanIsNull() {
            addCriterion("boolean_boolean is null");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanIsNotNull() {
            addCriterion("boolean_boolean is not null");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanEqualTo(Boolean value) {
            addCriterion("boolean_boolean =", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanNotEqualTo(Boolean value) {
            addCriterion("boolean_boolean <>", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanGreaterThan(Boolean value) {
            addCriterion("boolean_boolean >", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("boolean_boolean >=", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanLessThan(Boolean value) {
            addCriterion("boolean_boolean <", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanLessThanOrEqualTo(Boolean value) {
            addCriterion("boolean_boolean <=", value, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanIn(List<Boolean> values) {
            addCriterion("boolean_boolean in", values, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanNotIn(List<Boolean> values) {
            addCriterion("boolean_boolean not in", values, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanBetween(Boolean value1, Boolean value2) {
            addCriterion("boolean_boolean between", value1, value2, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andBooleanBooleanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("boolean_boolean not between", value1, value2, "booleanBoolean");
            return (Criteria) this;
        }

        public Criteria andCharacterVaryingStringLikeInsensitive(String value) {
            addCriterion("upper(character_varying_string) like", value.toUpperCase(), "characterVaryingString");
            return (Criteria) this;
        }

        public Criteria andVarcharStringLikeInsensitive(String value) {
            addCriterion("upper(varchar_string) like", value.toUpperCase(), "varcharString");
            return (Criteria) this;
        }

        public Criteria andCharacterStringLikeInsensitive(String value) {
            addCriterion("upper(character_string) like", value.toUpperCase(), "characterString");
            return (Criteria) this;
        }

        public Criteria andCharStringLikeInsensitive(String value) {
            addCriterion("upper(char_string) like", value.toUpperCase(), "charString");
            return (Criteria) this;
        }

        public Criteria andTextStringLikeInsensitive(String value) {
            addCriterion("upper(text_string) like", value.toUpperCase(), "textString");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample1
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample1
     *
     * @mbg.generated
     */
    public static class Criterion {
        private final String condition;
        private final String typeHandler;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}