package com.example.domain.example;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   サンプル１
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sample1
 */
@Data
public class Sample1 implements Serializable {
    /**
     * Database Column Remarks:
     *   数値・整数１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.integer_number
     *
     * @mbg.generated
     */
    private Integer integerNumber;

    /**
     * Database Column Remarks:
     *   数値・整数２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.real_number
     *
     * @mbg.generated
     */
    private Float realNumber;

    /**
     * Database Column Remarks:
     *   数値・小数１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.double_precision_number
     *
     * @mbg.generated
     */
    private Double doublePrecisionNumber;

    /**
     * Database Column Remarks:
     *   数値・小数２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.decimal_number
     *
     * @mbg.generated
     */
    private BigDecimal decimalNumber;

    /**
     * Database Column Remarks:
     *   数値・連番
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.serial_number
     *
     * @mbg.generated
     */
    private Integer serialNumber;

    /**
     * Database Column Remarks:
     *   文字列・可変長１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.character_varying_string
     *
     * @mbg.generated
     */
    private String characterVaryingString;

    /**
     * Database Column Remarks:
     *   文字列・可変長２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.varchar_string
     *
     * @mbg.generated
     */
    private String varcharString;

    /**
     * Database Column Remarks:
     *   文字列・固定長１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.character_string
     *
     * @mbg.generated
     */
    private String characterString;

    /**
     * Database Column Remarks:
     *   文字列・固定長２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.char_string
     *
     * @mbg.generated
     */
    private String charString;

    /**
     * Database Column Remarks:
     *   文字列・テキスト
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.text_string
     *
     * @mbg.generated
     */
    private String textString;

    /**
     * Database Column Remarks:
     *   日付・日付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.date_data
     *
     * @mbg.generated
     */
    private LocalDate dateData;

    /**
     * Database Column Remarks:
     *   日付・時刻１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.time_data
     *
     * @mbg.generated
     */
    private LocalTime timeData;

    /**
     * Database Column Remarks:
     *   日付・時刻２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.time_zone_data
     *
     * @mbg.generated
     */
    private LocalTime timeZoneData;

    /**
     * Database Column Remarks:
     *   日付・日時１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.timestamp_data
     *
     * @mbg.generated
     */
    private LocalDateTime timestampData;

    /**
     * Database Column Remarks:
     *   日付・日時２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.timestamp_zone_data
     *
     * @mbg.generated
     */
    private LocalDateTime timestampZoneData;

    /**
     * Database Column Remarks:
     *   真偽値１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.boolean_boolean
     *
     * @mbg.generated
     */
    private Boolean booleanBoolean;

    /**
     * Database Column Remarks:
     *   バイナリ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample1.binary_binary
     *
     * @mbg.generated
     */
    private byte[] binaryBinary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}