package com.example.domain.repository.fileupload;

import com.example.domain.model.TempFile;
import com.example.domain.model.TempFileExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TempFileRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    long countByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int deleteByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int insert(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int insertSelective(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithBLOBsWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithBLOBs(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    TempFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TempFile record, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TempFile record, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TempFile record, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempFile record);
}