package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;

/**
 * Database Table Remarks:
 * アカウント画像ファイル
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.account_image
 */
@Data
public class AccountImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.account_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account_image.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * 拡張子
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account_image.extension
     *
     * @mbg.generated
     */
    private String extension;
    /**
     * Database Column Remarks:
     * ファイル本体
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account_image.body
     *
     * @mbg.generated
     */
    private byte[] body;
}