package com.example.domain.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Database Table Remarks:
 *   アカウント画像ファイル
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_image
 */
@Data
public class AccountImage implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_image.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   拡張子
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_image.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     * Database Column Remarks:
     *   ファイル本体
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_image.body
     *
     * @mbg.generated
     */
    private byte[] body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}