package com.example.domain.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Database Table Remarks:
 *   アカウント
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account
 */
@Data
public class Account implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   プロフィール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.profile
     *
     * @mbg.generated
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}