package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;

/**
 * Database Table Remarks:
 * アカウント
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.account
 */
@Data
public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * パスワード
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.password
     *
     * @mbg.generated
     */
    private String password;
    /**
     * Database Column Remarks:
     * 名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.first_name
     *
     * @mbg.generated
     */
    private String firstName;
    /**
     * Database Column Remarks:
     * 姓
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.last_name
     *
     * @mbg.generated
     */
    private String lastName;
    /**
     * Database Column Remarks:
     * メールアドレス
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.email
     *
     * @mbg.generated
     */
    private String email;
    /**
     * Database Column Remarks:
     * URL
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.url
     *
     * @mbg.generated
     */
    private String url;
    /**
     * Database Column Remarks:
     * プロフィール
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.profile
     *
     * @mbg.generated
     */
    private String profile;
}