package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * パスワード再発行失敗履歴
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.failed_password_reissue
 */
@Data
public class FailedPasswordReissue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.failed_password_reissue
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * トークン
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.failed_password_reissue.token
     *
     * @mbg.generated
     */
    private String token;
    /**
     * Database Column Remarks:
     * 試行日時
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.failed_password_reissue.attempt_date
     *
     * @mbg.generated
     */
    private LocalDateTime attemptDate;
}