package com.example.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   認証失敗履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table failed_authentication
 */
@Data
public class FailedAuthentication implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failed_authentication.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   失敗日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failed_authentication.authentication_timestamp
     *
     * @mbg.generated
     */
    private LocalDateTime authenticationTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table failed_authentication
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}