package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * パスワード再発行認証情報
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.password_reissue_info
 */
@Data
public class PasswordReissueInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.password_reissue_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * トークン
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_reissue_info.token
     *
     * @mbg.generated
     */
    private String token;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_reissue_info.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * 秘密情報
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_reissue_info.secret
     *
     * @mbg.generated
     */
    private String secret;
    /**
     * Database Column Remarks:
     * 有効期限
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_reissue_info.expiry_date
     *
     * @mbg.generated
     */
    private LocalDateTime expiryDate;
}