package com.example.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   パスワード履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table password_history
 */
@Data
public class PasswordHistory implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_history.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   利用開始日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_history.use_from
     *
     * @mbg.generated
     */
    private LocalDateTime useFrom;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_history.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table password_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}