package com.example.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   パスワード再発行認証情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table password_reissue_info
 */
@Data
public class PasswordReissueInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_reissue_info.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_reissue_info.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   秘密情報
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_reissue_info.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     * Database Column Remarks:
     *   有効期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password_reissue_info.expiry_date
     *
     * @mbg.generated
     */
    private LocalDateTime expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table password_reissue_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}