package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * パスワード履歴
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.password_history
 */
@Data
public class PasswordHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.password_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_history.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * 利用開始日時
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_history.use_from
     *
     * @mbg.generated
     */
    private LocalDateTime useFrom;
    /**
     * Database Column Remarks:
     * パスワード
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.password_history.password
     *
     * @mbg.generated
     */
    private String password;
}