package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;

/**
 * Database Table Remarks:
 * ユーザ・ロール関連
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.role
 */
@Data
public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * ロール
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.role
     *
     * @mbg.generated
     */
    private String role;
}