package com.example.domain.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Database Table Remarks:
 *   ユーザ・ロール関連
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role
 */
@Data
public class Role implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   ロール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}