package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * 認証成功履歴
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.successful_authentication
 */
@Data
public class SuccessfulAuthentication implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.successful_authentication
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ユーザID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.successful_authentication.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     * Database Column Remarks:
     * 成功日時
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.successful_authentication.authentication_timestamp
     *
     * @mbg.generated
     */
    private LocalDateTime authenticationTimestamp;
}