package com.example.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   一時保存ファイル
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table temp_file
 */
@Data
public class TempFile implements Serializable {
    /**
     * Database Column Remarks:
     *   ID(内部番号)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   オリジナルファイル名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.original_name
     *
     * @mbg.generated
     */
    private String originalName;

    /**
     * Database Column Remarks:
     *   アップロード日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.uploaded_date
     *
     * @mbg.generated
     */
    private LocalDateTime uploadedDate;

    /**
     * Database Column Remarks:
     *   ファイル本体
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.body
     *
     * @mbg.generated
     */
    private byte[] body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}