package com.example.domain.model;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * 一時保存ファイル
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.temp_file
 */
@Data
public class TempFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.temp_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * ID(内部番号)
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.temp_file.id
     *
     * @mbg.generated
     */
    private String id;
    /**
     * Database Column Remarks:
     * オリジナルファイル名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.temp_file.original_name
     *
     * @mbg.generated
     */
    private String originalName;
    /**
     * Database Column Remarks:
     * アップロード日時
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.temp_file.uploaded_date
     *
     * @mbg.generated
     */
    private LocalDateTime uploadedDate;
    /**
     * Database Column Remarks:
     * ファイル本体
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.temp_file.body
     *
     * @mbg.generated
     */
    private byte[] body;
}