package com.example.domain.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public TmCodeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdShuIsNull() {
            addCriterion("cd_shu is null");
            return (Criteria) this;
        }

        public Criteria andCdShuIsNotNull() {
            addCriterion("cd_shu is not null");
            return (Criteria) this;
        }

        public Criteria andCdShuEqualTo(String value) {
            addCriterion("cd_shu =", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotEqualTo(String value) {
            addCriterion("cd_shu <>", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuGreaterThan(String value) {
            addCriterion("cd_shu >", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuGreaterThanOrEqualTo(String value) {
            addCriterion("cd_shu >=", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLessThan(String value) {
            addCriterion("cd_shu <", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLessThanOrEqualTo(String value) {
            addCriterion("cd_shu <=", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLike(String value) {
            addCriterion("cd_shu like", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotLike(String value) {
            addCriterion("cd_shu not like", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuIn(List<String> values) {
            addCriterion("cd_shu in", values, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotIn(List<String> values) {
            addCriterion("cd_shu not in", values, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuBetween(String value1, String value2) {
            addCriterion("cd_shu between", value1, value2, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotBetween(String value1, String value2) {
            addCriterion("cd_shu not between", value1, value2, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdCodeIsNull() {
            addCriterion("cd_code is null");
            return (Criteria) this;
        }

        public Criteria andCdCodeIsNotNull() {
            addCriterion("cd_code is not null");
            return (Criteria) this;
        }

        public Criteria andCdCodeEqualTo(String value) {
            addCriterion("cd_code =", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotEqualTo(String value) {
            addCriterion("cd_code <>", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeGreaterThan(String value) {
            addCriterion("cd_code >", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cd_code >=", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLessThan(String value) {
            addCriterion("cd_code <", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLessThanOrEqualTo(String value) {
            addCriterion("cd_code <=", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLike(String value) {
            addCriterion("cd_code like", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotLike(String value) {
            addCriterion("cd_code not like", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeIn(List<String> values) {
            addCriterion("cd_code in", values, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotIn(List<String> values) {
            addCriterion("cd_code not in", values, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeBetween(String value1, String value2) {
            addCriterion("cd_code between", value1, value2, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotBetween(String value1, String value2) {
            addCriterion("cd_code not between", value1, value2, "cdCode");
            return (Criteria) this;
        }

        public Criteria andKjShuIsNull() {
            addCriterion("kj_shu is null");
            return (Criteria) this;
        }

        public Criteria andKjShuIsNotNull() {
            addCriterion("kj_shu is not null");
            return (Criteria) this;
        }

        public Criteria andKjShuEqualTo(String value) {
            addCriterion("kj_shu =", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotEqualTo(String value) {
            addCriterion("kj_shu <>", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuGreaterThan(String value) {
            addCriterion("kj_shu >", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuGreaterThanOrEqualTo(String value) {
            addCriterion("kj_shu >=", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLessThan(String value) {
            addCriterion("kj_shu <", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLessThanOrEqualTo(String value) {
            addCriterion("kj_shu <=", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLike(String value) {
            addCriterion("kj_shu like", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotLike(String value) {
            addCriterion("kj_shu not like", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuIn(List<String> values) {
            addCriterion("kj_shu in", values, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotIn(List<String> values) {
            addCriterion("kj_shu not in", values, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuBetween(String value1, String value2) {
            addCriterion("kj_shu between", value1, value2, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotBetween(String value1, String value2) {
            addCriterion("kj_shu not between", value1, value2, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjCodeIsNull() {
            addCriterion("kj_code is null");
            return (Criteria) this;
        }

        public Criteria andKjCodeIsNotNull() {
            addCriterion("kj_code is not null");
            return (Criteria) this;
        }

        public Criteria andKjCodeEqualTo(String value) {
            addCriterion("kj_code =", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotEqualTo(String value) {
            addCriterion("kj_code <>", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeGreaterThan(String value) {
            addCriterion("kj_code >", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeGreaterThanOrEqualTo(String value) {
            addCriterion("kj_code >=", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLessThan(String value) {
            addCriterion("kj_code <", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLessThanOrEqualTo(String value) {
            addCriterion("kj_code <=", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLike(String value) {
            addCriterion("kj_code like", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotLike(String value) {
            addCriterion("kj_code not like", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeIn(List<String> values) {
            addCriterion("kj_code in", values, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotIn(List<String> values) {
            addCriterion("kj_code not in", values, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeBetween(String value1, String value2) {
            addCriterion("kj_code between", value1, value2, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotBetween(String value1, String value2) {
            addCriterion("kj_code not between", value1, value2, "kjCode");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1IsNull() {
            addCriterion("dt_joretsu1 is null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1IsNotNull() {
            addCriterion("dt_joretsu1 is not null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1EqualTo(Integer value) {
            addCriterion("dt_joretsu1 =", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotEqualTo(Integer value) {
            addCriterion("dt_joretsu1 <>", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1GreaterThan(Integer value) {
            addCriterion("dt_joretsu1 >", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1GreaterThanOrEqualTo(Integer value) {
            addCriterion("dt_joretsu1 >=", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1LessThan(Integer value) {
            addCriterion("dt_joretsu1 <", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1LessThanOrEqualTo(Integer value) {
            addCriterion("dt_joretsu1 <=", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1In(List<Integer> values) {
            addCriterion("dt_joretsu1 in", values, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotIn(List<Integer> values) {
            addCriterion("dt_joretsu1 not in", values, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1Between(Integer value1, Integer value2) {
            addCriterion("dt_joretsu1 between", value1, value2, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotBetween(Integer value1, Integer value2) {
            addCriterion("dt_joretsu1 not between", value1, value2, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2IsNull() {
            addCriterion("dt_joretsu2 is null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2IsNotNull() {
            addCriterion("dt_joretsu2 is not null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2EqualTo(Integer value) {
            addCriterion("dt_joretsu2 =", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotEqualTo(Integer value) {
            addCriterion("dt_joretsu2 <>", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2GreaterThan(Integer value) {
            addCriterion("dt_joretsu2 >", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2GreaterThanOrEqualTo(Integer value) {
            addCriterion("dt_joretsu2 >=", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2LessThan(Integer value) {
            addCriterion("dt_joretsu2 <", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2LessThanOrEqualTo(Integer value) {
            addCriterion("dt_joretsu2 <=", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2In(List<Integer> values) {
            addCriterion("dt_joretsu2 in", values, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotIn(List<Integer> values) {
            addCriterion("dt_joretsu2 not in", values, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2Between(Integer value1, Integer value2) {
            addCriterion("dt_joretsu2 between", value1, value2, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotBetween(Integer value1, Integer value2) {
            addCriterion("dt_joretsu2 not between", value1, value2, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtText1IsNull() {
            addCriterion("dt_text1 is null");
            return (Criteria) this;
        }

        public Criteria andDtText1IsNotNull() {
            addCriterion("dt_text1 is not null");
            return (Criteria) this;
        }

        public Criteria andDtText1EqualTo(String value) {
            addCriterion("dt_text1 =", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotEqualTo(String value) {
            addCriterion("dt_text1 <>", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1GreaterThan(String value) {
            addCriterion("dt_text1 >", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1GreaterThanOrEqualTo(String value) {
            addCriterion("dt_text1 >=", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1LessThan(String value) {
            addCriterion("dt_text1 <", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1LessThanOrEqualTo(String value) {
            addCriterion("dt_text1 <=", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1Like(String value) {
            addCriterion("dt_text1 like", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotLike(String value) {
            addCriterion("dt_text1 not like", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1In(List<String> values) {
            addCriterion("dt_text1 in", values, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotIn(List<String> values) {
            addCriterion("dt_text1 not in", values, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1Between(String value1, String value2) {
            addCriterion("dt_text1 between", value1, value2, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotBetween(String value1, String value2) {
            addCriterion("dt_text1 not between", value1, value2, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText2IsNull() {
            addCriterion("dt_text2 is null");
            return (Criteria) this;
        }

        public Criteria andDtText2IsNotNull() {
            addCriterion("dt_text2 is not null");
            return (Criteria) this;
        }

        public Criteria andDtText2EqualTo(String value) {
            addCriterion("dt_text2 =", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotEqualTo(String value) {
            addCriterion("dt_text2 <>", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2GreaterThan(String value) {
            addCriterion("dt_text2 >", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2GreaterThanOrEqualTo(String value) {
            addCriterion("dt_text2 >=", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2LessThan(String value) {
            addCriterion("dt_text2 <", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2LessThanOrEqualTo(String value) {
            addCriterion("dt_text2 <=", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2Like(String value) {
            addCriterion("dt_text2 like", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotLike(String value) {
            addCriterion("dt_text2 not like", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2In(List<String> values) {
            addCriterion("dt_text2 in", values, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotIn(List<String> values) {
            addCriterion("dt_text2 not in", values, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2Between(String value1, String value2) {
            addCriterion("dt_text2 between", value1, value2, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotBetween(String value1, String value2) {
            addCriterion("dt_text2 not between", value1, value2, "dtText2");
            return (Criteria) this;
        }

        public Criteria andNmNum1IsNull() {
            addCriterion("nm_num1 is null");
            return (Criteria) this;
        }

        public Criteria andNmNum1IsNotNull() {
            addCriterion("nm_num1 is not null");
            return (Criteria) this;
        }

        public Criteria andNmNum1EqualTo(BigDecimal value) {
            addCriterion("nm_num1 =", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotEqualTo(BigDecimal value) {
            addCriterion("nm_num1 <>", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1GreaterThan(BigDecimal value) {
            addCriterion("nm_num1 >", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nm_num1 >=", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1LessThan(BigDecimal value) {
            addCriterion("nm_num1 <", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("nm_num1 <=", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1In(List<BigDecimal> values) {
            addCriterion("nm_num1 in", values, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotIn(List<BigDecimal> values) {
            addCriterion("nm_num1 not in", values, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("nm_num1 between", value1, value2, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nm_num1 not between", value1, value2, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum2IsNull() {
            addCriterion("nm_num2 is null");
            return (Criteria) this;
        }

        public Criteria andNmNum2IsNotNull() {
            addCriterion("nm_num2 is not null");
            return (Criteria) this;
        }

        public Criteria andNmNum2EqualTo(BigDecimal value) {
            addCriterion("nm_num2 =", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotEqualTo(BigDecimal value) {
            addCriterion("nm_num2 <>", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2GreaterThan(BigDecimal value) {
            addCriterion("nm_num2 >", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nm_num2 >=", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2LessThan(BigDecimal value) {
            addCriterion("nm_num2 <", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("nm_num2 <=", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2In(List<BigDecimal> values) {
            addCriterion("nm_num2 in", values, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotIn(List<BigDecimal> values) {
            addCriterion("nm_num2 not in", values, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("nm_num2 between", value1, value2, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nm_num2 not between", value1, value2, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andTmDate1IsNull() {
            addCriterion("tm_date1 is null");
            return (Criteria) this;
        }

        public Criteria andTmDate1IsNotNull() {
            addCriterion("tm_date1 is not null");
            return (Criteria) this;
        }

        public Criteria andTmDate1EqualTo(LocalDateTime value) {
            addCriterion("tm_date1 =", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotEqualTo(LocalDateTime value) {
            addCriterion("tm_date1 <>", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1GreaterThan(LocalDateTime value) {
            addCriterion("tm_date1 >", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_date1 >=", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1LessThan(LocalDateTime value) {
            addCriterion("tm_date1 <", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_date1 <=", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1In(List<LocalDateTime> values) {
            addCriterion("tm_date1 in", values, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotIn(List<LocalDateTime> values) {
            addCriterion("tm_date1 not in", values, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_date1 between", value1, value2, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_date1 not between", value1, value2, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate2IsNull() {
            addCriterion("tm_date2 is null");
            return (Criteria) this;
        }

        public Criteria andTmDate2IsNotNull() {
            addCriterion("tm_date2 is not null");
            return (Criteria) this;
        }

        public Criteria andTmDate2EqualTo(LocalDateTime value) {
            addCriterion("tm_date2 =", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotEqualTo(LocalDateTime value) {
            addCriterion("tm_date2 <>", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2GreaterThan(LocalDateTime value) {
            addCriterion("tm_date2 >", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_date2 >=", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2LessThan(LocalDateTime value) {
            addCriterion("tm_date2 <", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_date2 <=", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2In(List<LocalDateTime> values) {
            addCriterion("tm_date2 in", values, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotIn(List<LocalDateTime> values) {
            addCriterion("tm_date2 not in", values, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_date2 between", value1, value2, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_date2 not between", value1, value2, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNull() {
            addCriterion("cd_teishi is null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNotNull() {
            addCriterion("cd_teishi is not null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiEqualTo(String value) {
            addCriterion("cd_teishi =", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotEqualTo(String value) {
            addCriterion("cd_teishi <>", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThan(String value) {
            addCriterion("cd_teishi >", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThanOrEqualTo(String value) {
            addCriterion("cd_teishi >=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThan(String value) {
            addCriterion("cd_teishi <", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThanOrEqualTo(String value) {
            addCriterion("cd_teishi <=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLike(String value) {
            addCriterion("cd_teishi like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotLike(String value) {
            addCriterion("cd_teishi not like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIn(List<String> values) {
            addCriterion("cd_teishi in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotIn(List<String> values) {
            addCriterion("cd_teishi not in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiBetween(String value1, String value2) {
            addCriterion("cd_teishi between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotBetween(String value1, String value2) {
            addCriterion("cd_teishi not between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNull() {
            addCriterion("cd_lu_kaisha is null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNotNull() {
            addCriterion("cd_lu_kaisha is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaEqualTo(String value) {
            addCriterion("cd_lu_kaisha =", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotEqualTo(String value) {
            addCriterion("cd_lu_kaisha <>", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThan(String value) {
            addCriterion("cd_lu_kaisha >", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("cd_lu_kaisha >=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThan(String value) {
            addCriterion("cd_lu_kaisha <", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThanOrEqualTo(String value) {
            addCriterion("cd_lu_kaisha <=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLike(String value) {
            addCriterion("cd_lu_kaisha like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotLike(String value) {
            addCriterion("cd_lu_kaisha not like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIn(List<String> values) {
            addCriterion("cd_lu_kaisha in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotIn(List<String> values) {
            addCriterion("cd_lu_kaisha not in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaBetween(String value1, String value2) {
            addCriterion("cd_lu_kaisha between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotBetween(String value1, String value2) {
            addCriterion("cd_lu_kaisha not between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("cd_lu_user is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("cd_lu_user is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("cd_lu_user =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("cd_lu_user <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("cd_lu_user >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("cd_lu_user >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("cd_lu_user <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("cd_lu_user <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("cd_lu_user like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("cd_lu_user not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("cd_lu_user in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("cd_lu_user not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("cd_lu_user between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("cd_lu_user not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("tm_lu is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("tm_lu is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("tm_lu =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("tm_lu <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("tm_lu >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_lu >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("tm_lu <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_lu <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("tm_lu in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("tm_lu not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_lu between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_lu not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_code
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}