package com.example.domain.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   コード
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tm_code
 */
@Data
public class TmCode implements Serializable {
    /**
     * Database Column Remarks:
     *   種別コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.cd_shu
     *
     * @mbg.generated
     */
    private String cdShu;

    /**
     * Database Column Remarks:
     *   コード値
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.cd_code
     *
     * @mbg.generated
     */
    private String cdCode;

    /**
     * Database Column Remarks:
     *   種別名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.kj_shu
     *
     * @mbg.generated
     */
    private String kjShu;

    /**
     * Database Column Remarks:
     *   コード名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.kj_code
     *
     * @mbg.generated
     */
    private String kjCode;

    /**
     * Database Column Remarks:
     *   序列１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.dt_joretsu1
     *
     * @mbg.generated
     */
    private Integer dtJoretsu1;

    /**
     * Database Column Remarks:
     *   序列２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.dt_joretsu2
     *
     * @mbg.generated
     */
    private Integer dtJoretsu2;

    /**
     * Database Column Remarks:
     *   テキスト１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.dt_text1
     *
     * @mbg.generated
     */
    private String dtText1;

    /**
     * Database Column Remarks:
     *   テキスト２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.dt_text2
     *
     * @mbg.generated
     */
    private String dtText2;

    /**
     * Database Column Remarks:
     *   数値１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.nm_num1
     *
     * @mbg.generated
     */
    private BigDecimal nmNum1;

    /**
     * Database Column Remarks:
     *   数値２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.nm_num2
     *
     * @mbg.generated
     */
    private BigDecimal nmNum2;

    /**
     * Database Column Remarks:
     *   日付１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.tm_date1
     *
     * @mbg.generated
     */
    private LocalDateTime tmDate1;

    /**
     * Database Column Remarks:
     *   日付２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.tm_date2
     *
     * @mbg.generated
     */
    private LocalDateTime tmDate2;

    /**
     * Database Column Remarks:
     *   使用停止区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.cd_teishi
     *
     * @mbg.generated
     */
    private String cdTeishi;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.cd_lu_kaisha
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.cd_lu_user
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_code.tm_lu
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}