package com.example.domain.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TtJohoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public TtJohoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdSeqIsNull() {
            addCriterion("cd_seq is null");
            return (Criteria) this;
        }

        public Criteria andCdSeqIsNotNull() {
            addCriterion("cd_seq is not null");
            return (Criteria) this;
        }

        public Criteria andCdSeqEqualTo(BigDecimal value) {
            addCriterion("cd_seq =", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotEqualTo(BigDecimal value) {
            addCriterion("cd_seq <>", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqGreaterThan(BigDecimal value) {
            addCriterion("cd_seq >", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cd_seq >=", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqLessThan(BigDecimal value) {
            addCriterion("cd_seq <", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cd_seq <=", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqIn(List<BigDecimal> values) {
            addCriterion("cd_seq in", values, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotIn(List<BigDecimal> values) {
            addCriterion("cd_seq not in", values, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cd_seq between", value1, value2, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cd_seq not between", value1, value2, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIsNull() {
            addCriterion("cd_browse is null");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIsNotNull() {
            addCriterion("cd_browse is not null");
            return (Criteria) this;
        }

        public Criteria andCdBrowseEqualTo(String value) {
            addCriterion("cd_browse =", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotEqualTo(String value) {
            addCriterion("cd_browse <>", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseGreaterThan(String value) {
            addCriterion("cd_browse >", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseGreaterThanOrEqualTo(String value) {
            addCriterion("cd_browse >=", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLessThan(String value) {
            addCriterion("cd_browse <", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLessThanOrEqualTo(String value) {
            addCriterion("cd_browse <=", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLike(String value) {
            addCriterion("cd_browse like", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotLike(String value) {
            addCriterion("cd_browse not like", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIn(List<String> values) {
            addCriterion("cd_browse in", values, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotIn(List<String> values) {
            addCriterion("cd_browse not in", values, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseBetween(String value1, String value2) {
            addCriterion("cd_browse between", value1, value2, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotBetween(String value1, String value2) {
            addCriterion("cd_browse not between", value1, value2, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIsNull() {
            addCriterion("cd_category is null");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIsNotNull() {
            addCriterion("cd_category is not null");
            return (Criteria) this;
        }

        public Criteria andCdCategoryEqualTo(String value) {
            addCriterion("cd_category =", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotEqualTo(String value) {
            addCriterion("cd_category <>", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryGreaterThan(String value) {
            addCriterion("cd_category >", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("cd_category >=", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLessThan(String value) {
            addCriterion("cd_category <", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLessThanOrEqualTo(String value) {
            addCriterion("cd_category <=", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLike(String value) {
            addCriterion("cd_category like", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotLike(String value) {
            addCriterion("cd_category not like", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIn(List<String> values) {
            addCriterion("cd_category in", values, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotIn(List<String> values) {
            addCriterion("cd_category not in", values, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryBetween(String value1, String value2) {
            addCriterion("cd_category between", value1, value2, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotBetween(String value1, String value2) {
            addCriterion("cd_category not between", value1, value2, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIsNull() {
            addCriterion("tm_release is null");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIsNotNull() {
            addCriterion("tm_release is not null");
            return (Criteria) this;
        }

        public Criteria andTmReleaseEqualTo(LocalDateTime value) {
            addCriterion("tm_release =", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotEqualTo(LocalDateTime value) {
            addCriterion("tm_release <>", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseGreaterThan(LocalDateTime value) {
            addCriterion("tm_release >", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_release >=", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseLessThan(LocalDateTime value) {
            addCriterion("tm_release <", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_release <=", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIn(List<LocalDateTime> values) {
            addCriterion("tm_release in", values, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotIn(List<LocalDateTime> values) {
            addCriterion("tm_release not in", values, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_release between", value1, value2, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_release not between", value1, value2, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andKjTitleIsNull() {
            addCriterion("kj_title is null");
            return (Criteria) this;
        }

        public Criteria andKjTitleIsNotNull() {
            addCriterion("kj_title is not null");
            return (Criteria) this;
        }

        public Criteria andKjTitleEqualTo(String value) {
            addCriterion("kj_title =", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotEqualTo(String value) {
            addCriterion("kj_title <>", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleGreaterThan(String value) {
            addCriterion("kj_title >", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleGreaterThanOrEqualTo(String value) {
            addCriterion("kj_title >=", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLessThan(String value) {
            addCriterion("kj_title <", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLessThanOrEqualTo(String value) {
            addCriterion("kj_title <=", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLike(String value) {
            addCriterion("kj_title like", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotLike(String value) {
            addCriterion("kj_title not like", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleIn(List<String> values) {
            addCriterion("kj_title in", values, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotIn(List<String> values) {
            addCriterion("kj_title not in", values, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleBetween(String value1, String value2) {
            addCriterion("kj_title between", value1, value2, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotBetween(String value1, String value2) {
            addCriterion("kj_title not between", value1, value2, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIsNull() {
            addCriterion("dt_oshirase is null");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIsNotNull() {
            addCriterion("dt_oshirase is not null");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseEqualTo(String value) {
            addCriterion("dt_oshirase =", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotEqualTo(String value) {
            addCriterion("dt_oshirase <>", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseGreaterThan(String value) {
            addCriterion("dt_oshirase >", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseGreaterThanOrEqualTo(String value) {
            addCriterion("dt_oshirase >=", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLessThan(String value) {
            addCriterion("dt_oshirase <", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLessThanOrEqualTo(String value) {
            addCriterion("dt_oshirase <=", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLike(String value) {
            addCriterion("dt_oshirase like", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotLike(String value) {
            addCriterion("dt_oshirase not like", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIn(List<String> values) {
            addCriterion("dt_oshirase in", values, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotIn(List<String> values) {
            addCriterion("dt_oshirase not in", values, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseBetween(String value1, String value2) {
            addCriterion("dt_oshirase between", value1, value2, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotBetween(String value1, String value2) {
            addCriterion("dt_oshirase not between", value1, value2, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andTmLimitIsNull() {
            addCriterion("tm_limit is null");
            return (Criteria) this;
        }

        public Criteria andTmLimitIsNotNull() {
            addCriterion("tm_limit is not null");
            return (Criteria) this;
        }

        public Criteria andTmLimitEqualTo(LocalDateTime value) {
            addCriterion("tm_limit =", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotEqualTo(LocalDateTime value) {
            addCriterion("tm_limit <>", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitGreaterThan(LocalDateTime value) {
            addCriterion("tm_limit >", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_limit >=", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitLessThan(LocalDateTime value) {
            addCriterion("tm_limit <", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_limit <=", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitIn(List<LocalDateTime> values) {
            addCriterion("tm_limit in", values, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotIn(List<LocalDateTime> values) {
            addCriterion("tm_limit not in", values, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_limit between", value1, value2, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_limit not between", value1, value2, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andDtFileIsNull() {
            addCriterion("dt_file is null");
            return (Criteria) this;
        }

        public Criteria andDtFileIsNotNull() {
            addCriterion("dt_file is not null");
            return (Criteria) this;
        }

        public Criteria andDtFileEqualTo(String value) {
            addCriterion("dt_file =", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotEqualTo(String value) {
            addCriterion("dt_file <>", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileGreaterThan(String value) {
            addCriterion("dt_file >", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileGreaterThanOrEqualTo(String value) {
            addCriterion("dt_file >=", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLessThan(String value) {
            addCriterion("dt_file <", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLessThanOrEqualTo(String value) {
            addCriterion("dt_file <=", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLike(String value) {
            addCriterion("dt_file like", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotLike(String value) {
            addCriterion("dt_file not like", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileIn(List<String> values) {
            addCriterion("dt_file in", values, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotIn(List<String> values) {
            addCriterion("dt_file not in", values, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileBetween(String value1, String value2) {
            addCriterion("dt_file between", value1, value2, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotBetween(String value1, String value2) {
            addCriterion("dt_file not between", value1, value2, "dtFile");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("cd_lu_user is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("cd_lu_user is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("cd_lu_user =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("cd_lu_user <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("cd_lu_user >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("cd_lu_user >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("cd_lu_user <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("cd_lu_user <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("cd_lu_user like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("cd_lu_user not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("cd_lu_user in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("cd_lu_user not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("cd_lu_user between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("cd_lu_user not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("tm_lu is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("tm_lu is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("tm_lu =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("tm_lu <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("tm_lu >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_lu >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("tm_lu <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("tm_lu <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("tm_lu in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("tm_lu not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_lu between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("tm_lu not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_joho
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_joho
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}